services:
  db:
    image: mariadb:11.1.2
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "wM1LKvy8"
    volumes:
      - "./data/mariadb_data:/var/lib/mysql"
    ports:
      - "5036:3306"